namespace:
  label: techtrends-staging
  name: staging
image:
  repository: maletq/techtrends
  tag: latest
  pullPolicy: IfNotPresent
service:
  port: 5111  
replicaCount: 3
resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    cpu: 500m
    memory: 128Mi

