namespace:
  label: techtrends-prod
  name: prod
image:
  repository: maletq/techtrends
  tag: latest
  image pullPolicy: Always
service:
  port: 7111  
replicaCount: 5
resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
containerPort: 3111
livenessProbe:
  httpGet:
    path: /healthz
    port: 3111
readinessProbe:
  httpGet:
    path: /healthz
    port: 3111

