namespace:
  name: sandbox
image:
  repository: maletq/techtrends
  tag: latest
  pullPolicy: IfNotPresent
service:
    port: 4111
    targetPort: 3111
    protocol: TCP
    type: ClusterIP 
replicaCount: 1
resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
containerPort: 3111
livenessProbe:
  httpGet:
    path: /healthz
    port: 3111
readinessProbe:
  httpGet:
    path: /healthz
    port: 3111
