apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-techtrends-sandbox
  namespace: sandbox
spec:
  source:
    helm:
      valueFiles:
      - Values.yaml 
    path: project1/helm
    repoURL: https://github.com/malet-pr/udacitySuseNanodegree
    targetRevision: HEAD
  project: default  