apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-techtrends-staging
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    helm:
      valueFiles:
        - Values-staging.yaml
    path: project1/helm
    repoURL: https://github.com/malet-pr/udacitySuseNanodegree
    targetRevision: HEAD
  project: default
