apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    helm:
      valueFiles:
      - Values-prod.yaml 
    path: project1/helm
    repoURL: https://github.com/malet-pr/udacitySuseNanodegree
    targetRevision: HEAD
  project: default  